#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

seconds_array = (1..10).to_a

tests = seconds_array.map { |n| { file: "spec/foo_#{n}_spec.rb", run_time: n.to_f } }
File.write(
  'circle-test-results/results.json',
  JSON.pretty_generate(tests: tests)
)

# ./circle-test-results/results.json
# {
#   "tests": [
#     {
#       "file": "1",
#       "run_time": 1.0
#     },
#     {
#       "file": "2",
#       "run_time": 2.0
#     },
#     ...
#   ]
# }

puts File.read('circle-test-results/results.json')

string = seconds_array.map { |n| "spec/foo_#{n}_spec.rb" }.join("\n")
File.write('list', string)
puts `cat list | circleci tests split --split-by=timings`
