#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

def generate_results_json(file_name_list)
  # This method generates:
  #
  # {
  #   "tests": [
  #     {
  #       "file": "1",
  #       "run_time": 1.0
  #     },
  #     {
  #       "file": "2",
  #       "run_time": 2.0
  #     },
  #     ...
  #   ]
  # }

  tests = file_name_list.map { |n| { file: n.to_s, run_time: n.to_f } }
  File.write(
    'circle-test-results/results.json',
    JSON.pretty_generate(tests: tests)
  )
end

file_name_list = [2, 3, 4, 5, 6, 10]

# result:
# [10]
# [6, 3, 2]
# [5, 4]

# best:
# [10]
# [6, 4]
# [5, 3, 2]

generate_results_json(file_name_list)

File.write('list', file_name_list.map(&:to_s).join("\n"))

require 'benchmark'

Benchmark.bmbm do |x|
  x.report('cat') { 100.times { `cat list` } }
  x.report('cat + split') { 100.times { `cat list | CIRCLE_NODE_INDEX=1 circleci tests split --split-by=timings` } }
  x.report('cat + custom split') { 100.times { `cat list | CIRCLE_NODE_INDEX=1 ./circleci-tests-split-split-by-timings` } }
end
